### ISSUE TITLE
BGM stops after continue

### ISSUE THREAD

**Issue by Lemongrwab** [vertrex/Arcade-JujuDensetsu_MiSTer#2]
Sometimes background music stops after continue screen, if you loose a life then music comes back.

**Comment by vertrex** [comment]
Thank you for the bug report, I will try to fix, but it's difficult to reproduce. Does it also happen if you don't use the "pause" button during the game (showing the contributors list) ?

**Comment by Lemongrwab** [comment]
After trying reproduce, it happens even before continue. This happens very randomly when I lose 1up. BGM stops without touching pause (contributors list) button

**Comment by vertrex** [comment]
Please submit your issue if not solved to https://github.com/jotego/jtcores I will archive this repository and submit update directly on jtcores repository
