### ISSUE TITLE
Little mistake

### ISSUE THREAD

**Issue by Lemongrwab** [vertrex/Arcade-JujuDensetsu_MiSTer#3]
In release section  "copy Toki.mra in the _Arcade/ directory" is wrong it's Toki.rbf

**Comment by vertrex** [comment]
Thank you, I updated the release.
The core is also available via update_all.sh via the unofficial cores list.

**Comment by vertrex** [comment]
Thank you, I updated the release.
The core is also available via update_all.sh via the unofficial cores list.
