### ISSUE TITLE
toki dont work on 15khz arcade monitor

### ISSUE THREAD

**Issue by vastago** [vertrex/Arcade-JujuDensetsu_MiSTer#7]

**Comment by vertrex** [comment]
Can you try this release : https://github.com/vertrex/Arcade-JujuDensetsu_MiSTer/releases/tag/1.1 ? 
Can you describe in more details what happened ?

**Comment by vastago** [comment]
ok, there are people that it does work for them on 15khz monitors. But not in my case, is it possible that my monitor does not support that frequency? 
![tokiCore](https://github.com/vertrex/Arcade-JujuDensetsu_MiSTer/assets/47063821/2175a118-2169-46ff-948f-c6fb0db08b5a)

**Comment by vastago** [comment]
I have tried this in mister.ini but it does not work:
; Arcade cores
[TOKI]
forced_scandoubler=0

**Comment by vertrex** [comment]
Please submit your issue if not solved to https://github.com/jotego/jtcores I will archive this repository and submit update directly on jtcores repository
