### ISSUE TITLE
Direct video output via HDMI seems not correct

### ISSUE THREAD

**Issue by heinzgruber** [vertrex/Arcade-JujuDensetsu_MiSTer#8]
Hi,
i'm using the scaler Retrotink 4K with my MiSter. With direct_video=1 in the MiSTer.ini the native core resolution is directly passed to the scaler. With the new framework (DV1 metadata passed to the scaler for auto crop and Decimation) this already works for many consoles and acrade cores from Jotego. But with the Toki core the picture keeps shaking briefly looks like some kind of sync problem. Strange is that the Retrotink 4K stats shows it's getting DV1 metadata. 

edit:
i use the toki.zip from update_all which i executed a few minutes ago. So i think i'm already using Toki core 1.1.

edit2:
strangly the game show up in _Arcade/cores/ as jttoki.rbf. and it seems that the files form update_all are version 1.0. i've just replaced the files with 1.1 manually but the problem is still there.

**Comment by vertrex** [comment]
Please submit your issue if not solved to https://github.com/jotego/jtcores I will archive this repository and submit update directly on jtcores repostiory
