### ISSUE TITLE
Sound effects are off 

### ISSUE THREAD

**Issue by bazset** [vertrex/Arcade-JujuDensetsu_MiSTer#9]
The sound effects on both the mister and pocket core are off.  Tokis death sound is really high pitched.  The sound of the enemies jumping is off. The sound of Toki using the 16ton see saw is off. As well as other sounds.

**Comment by vertrex** [comment]
The issue should be fixed, see : https://github.com/jotego/jtcores/issues/650
I commit update on jotego repository directly, I will archive this repository as it's easier to have all in one place. 
Please submit issue in jotego/jtcores in the futur. 

Thank you !
